import "./globals.css";
import { Inter } from "next/font/google";
import { Provider } from "@/store/Provider";
import { GlobalStyle } from "@/styles/globalStyle";
import { NextIntlClientProvider } from "next-intl";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  return (
    <html lang={locale}>
      <body className={inter.className}>
        <NextIntlClientProvider locale={locale}>
          <Provider>{children}</Provider>
        </NextIntlClientProvider>

        <GlobalStyle />
      </body>
    </html>
  );
}
